import React,{useEffect,useState}from'react';
import{getMyLecturerProfile,getMyTeachingModules,getRegisteredStudentsWithGrades,saveIndividualGrade}from'../services/moduleGrades';
import{getLecturerModuleGradeSummary,publishModuleGradesSafely}from'../services/gradePublish';
import{createGradeNotifications}from'../services/gradeNotifications';
import{createPublishBatch}from'../services/gradeAudit';

export default function ModuleGradePublisher(){
 const[lecturer,setLecturer]=useState(null),[mods,setMods]=useState([]),[mid,setMid]=useState(''),[rows,setRows]=useState([]),[scores,setScores]=useState({}),[summary,setSummary]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const l=await getMyLecturerProfile();setLecturer(l);setMods(await getMyTeachingModules(l.id));}catch(e){setMsg(e.message)}})()},[]);
 async function load(id){setMid(id);setMsg('');setRows([]);setSummary(null);if(!id)return;try{const r=await getRegisteredStudentsWithGrades(id);setRows(r);setScores(Object.fromEntries(r.map(x=>[x.id,x.gradeRecord?.score??''])));setSummary(await getLecturerModuleGradeSummary(id))}catch(e){setMsg(e.message)}}
 async function saveRow(r){try{setBusy(true);const g=await saveIndividualGrade({lecturerId:lecturer.id,moduleId:mid,studentId:r.id,score:scores[r.id]});setRows(rs=>rs.map(x=>x.id===r.id?{...x,gradeRecord:g}:x));setSummary(await getLecturerModuleGradeSummary(mid));setMsg(`Grade saved for ${r.student_id}.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function publish(){try{setBusy(true);const result=await publishModuleGradesSafely({moduleId:mid,lecturerId:lecturer.id});if(result.published.length){await createPublishBatch({moduleId:mid,lecturerId:lecturer.id,publishedCount:result.published.length});await createGradeNotifications({moduleId:mid,lecturerName:lecturer.full_name});}setSummary(await getLecturerModuleGradeSummary(mid));setRows(await getRegisteredStudentsWithGrades(mid));setMsg(`${result.published.length} individual grade(s) published and notifications sent.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="v22-wrap"><section className="v22-card"><h2>Module Grade Distribution</h2><p>Every registered Student ID must have a grade before publishing.</p>{msg&&<div className="v22-msg">{msg}</div>}{<select value={mid} onChange={e=>load(e.target.value)}><option value="">Select module</option>{mods.map(m=><option key={m.id} value={m.id}>{m.code} — {m.title}</option>)}</select>}{summary&&<div className="v22-summary"><span>Registered: <b>{summary.total}</b></span><span>Grades entered: <b>{summary.entered}</b></span><span>Published: <b>{summary.published}</b></span></div>}{mid&&<button className="v22-publish" disabled={busy||!summary||summary.entered!==summary.total} onClick={publish}>{summary&&summary.published===summary.total?'All Grades Published':'Publish All Grades'}</button>}</section>{mid&&<section className="v22-card"><h3>Individual Student Grades</h3>{rows.map(r=><div className="v22-row" key={r.id}><div><b>{r.student_id}</b><span>{r.full_name}</span></div><input type="number" min="0" max="100" value={scores[r.id]??''} disabled={r.gradeRecord?.published} onChange={e=>setScores({...scores,[r.id]:e.target.value})}/><span>{r.gradeRecord?.published?'Published':'Draft'}</span>{!r.gradeRecord?.published&&<button disabled={busy} onClick={()=>saveRow(r)}>Save</button>}</div>)}</section>}</div>
}
